modify native library build script to build wiringPi library

diff --git a/lib/src/native/build_lib b/lib/src/native/build_lib
--- a/lib/src/native/build_lib
+++ b/lib/src/native/build_lib
@@ -20,15 +20,36 @@ set -e
 #DARTSDK=$(dirname $DARTBIN)
 DARTSDK=$2
 
-# The package's tool/src directory
 cd $(dirname $0)
 echo building in `pwd`
 
-# Build the wiring pi library
-#cd wiringPi
-#sudo make install
-#cd ..
+####################################################################
+# Build the wiring pi library... copied from wiringPi/build
 
+cd wiringPi
+hardware=`fgrep Hardware /proc/cpuinfo | head -1 | awk '{ print $3 }'`
+
+check_make_ok() {
+  if [ $? != 0 ]; then
+    echo ""
+    echo "Make Failed..."
+    echo "Please check the messages and fix any problems."
+    echo "If you're still stuck, then please open an issue at 
+    echo "https://github.com/danrubel/dart_rpi_gpio/issues"
+    echo "with all the output and as many details as you can"
+    exit 1
+  fi
+}
+
+make -j5
+check_make_ok
+sudo make install
+check_make_ok
+
+####################################################################
+# Build rpi_gpio native library
+
+cd $(dirname $0)
 g++ -fPIC -I$DARTSDK/ -c rpi_gpio_ext.cc
 gcc -shared -Wl,wiringPi/wiringPi.o,wiringPi/softPwm.o,wiringPi/softTone.o,-soname,librpi_gpio_ext.so -o librpi_gpio_ext.so rpi_gpio_ext.o
 
